# Generated by Django 5.0.6 on 2025-04-11 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_celular_usuario_endereco_usuario_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='timeId',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
