# Generated by Django 5.0.6 on 2025-04-11 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_alter_usuario_timeid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='timeId',
        ),
    ]
